SUBDIRS = \
          freertos.armv7m.ek-tm4c123gxl \
          freertos.armv7m.ek-tm4c1294xl \
          freertos.armv7m.ti-launchpad-cc3220sf \
          freertos.armv7m.z-dev-board-123 \
          js.emscripten \
          linux.armv7a \
          linux.x86 \


# broken
# freertos.armv7m.st-stm32f103rb-olimexino \
# freertos.armv7m.bracz-acc2 \
# freertos.armv7m.bracz-acc3 \

include $(OPENMRNPATH)/etc/recurse.mk
