SUBDIRS = \
	freertos.armv7m.st-maple-cmsis \
	freertos.armv7m.st-stm32f303-discovery \
	freertos.armv7m.st-stm32f303re-nucleo \
	freertos.armv7m.ti-launchpad-lm4f120xl \
	freertos.armv7m.ti-launchpad-tm4c129 \

# broken
#	freertos.armv7m.ti-launchpad-cc3200 \
#	freertos.armv7m.bracz-acc \

include $(OPENMRNPATH)/etc/recurse.mk
