SUBDIRS = \
	freertos.armv4t.panda2 \
	freertos.armv6m.lpcxpresso-11C24 \
	freertos.armv7m.lpc1768-mbed \
	freertos.armv7m.mbed-1768 \

	freertos.mips4k.pic32mx.lccbuffer \

# broken
#	freertos.armv7m.ti-launchpad-cc3200 \
#	freertos.armv7m.bracz-acc \

include $(OPENMRNPATH)/etc/recurse.mk
