SUBDIRS = linux.x86 \
        linux.armv7a \
        linux.llvm \
        mach.x86_64 \
        freertos.armv7m.ek-lm4f120xl \
        freertos.armv7m.ek-tm4c123gxl \
        freertos.armv7m.ek-tm4c1294xl \
        freertos.armv7m.st-stm32l432kc-nucleo \
        js.emscripten \


include $(OPENMRNPATH)/etc/recurse.mk
