SUBDIRS = linux.x86 \
        linux.armv7a \
        linux.llvm \
        mach.x86_64 \
        freertos.armv7m.ek-lm4f120xl \
        freertos.armv7m.ek-tm4c123gxl \
        freertos.armv7m.ek-tm4c1294xl \
	freertos.armv7m.st-stm32f103rb-olimexino \
        freertos.armv7m.st-stm32f303-discovery \
        freertos.armv7m.st-stm32f303re-nucleo-dev-board \
        freertos.armv7m.st-stm32l432kc-nucleo \
	freertos.armv7m.st-maple-cmsis \
        js.emscripten \


#doesn't fit into flash. Let's retire this.
#freertos.armv7m.st-maple-cmsis \

include $(OPENMRNPATH)/etc/recurse.mk
