SUBDIRS = \
    freertos.armv7m.ek-tm4c123gxl \
    freertos.armv7m.ek-tm4c1294xl \
    linux.armv7a \
    linux.x86 \
    mach.x86_64


#	freertos.armv7m.lpc1768-mbed \
#	linux.x86 \

include $(OPENMRNPATH)/etc/recurse.mk
