SUBDIRS = linux.x86 \
          linux.llvm \
          linux.armv7a \
          freertos.armv7m \
          mach.x86_64 \
          bare.armv7m \
          js.emscripten \
          mingw.x86 \


          #test
          #nuttx.armv7m \

include $(OPENMRNPATH)/etc/recurse.mk
