SUBDIRS = linux.x86 \
          linux.llvm \
          linux.armv7a \
          freertos.armv7m \
          mach.x86_64 \
          bare.armv7m \
          js.emscripten \


          #test

include $(OPENMRNPATH)/etc/recurse.mk
